In [6]:
import numpy as np
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

The *axis* is the array axis along which the maximum is taken.

axis=0 is "**columns**"

In [4]:
np.argmax(a, axis=0)

array([1, 1, 1])

We get an array returning with the index of the maximum value across each of the columns - so for column 0 (i.e. values 0 and 3) the maximum is at index 1 (i.e. 3) - the same is true for the other columns too (1 and 4, and 2 and 5).

axis=1 is "**rows**":

In [5]:
np.argmax(a, axis=1)

array([2, 2])

So again here, we're getting the array of indexes for the *rows* of the array.

So here, for each row:
 - [0, 1, 2]
 - [3, 4, 5]
 
We get the index of the maximum value, which is 2 in both cases (i.e. values 2 and 5 are the maximum in their respective rows.